[workspace]
members = [".", "client", "server"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
bfbb = "0.2.1"
clash = { path = "." }
env_logger = "0.9"
log = "0.4"
thiserror = "1"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "io-util",
    "net",
    "macros",
    "sync",
    "time",
] }

# Remove unneeded debug info from linux binaries
[profile.release]
strip = true

# Optimize our dependencies for better performance when debugging
[profile.dev.package."*"]
opt-level = 3

# Don't optimize on CI though
[profile.ci]
inherits = "dev"

[profile.ci.package."*"]
opt-level = 0

# Lib Package

[package]
name = "clash"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
bfbb = { workspace = true, features = ["serde"] }
log.workspace = true
thiserror.workspace = true
tokio.workspace = true

bincode = "1"
bytes = "1"
epaint = "0.19"
serde = { version = "1", features = ["derive"] }
strum = "0.24.1"
strum_macros = "0.24.1"
