[package]
name = "clash"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["client", "server"]

# Remove unneeded debug info from linux binaries
[profile.release]
strip = true

# Optimize our dependencies for better performance when debugging
[profile.dev.package."*"]
opt-level = 3

# Don't optimize on CI though
[profile.ci]
inherits = "dev"

[profile.ci.package."*"]
opt-level = 0

[dependencies]
bfbb = { version = "0.2", features = ["serde"]}
tokio = { version = "1", features = ["rt", "rt-multi-thread", "io-util", "net", "macros"] }
epaint = "0.19"

bincode = "1"
bytes = "1"
serde = { version = "1", features = ["derive"] }

thiserror = "1"
anyhow = "1"

log = "0.4"
