[package]
name = "server"
version = "0.1.0"
edition = "2021"

[package.metadata.release]
consolidate-commits = true
publish = false
shared-version = true
tag = false

[dependencies]
clash = { path="../clash" }