on:
  push:
    branch:
      - testrelease
    tags:
      - v*.*.*

name: Create Release

jobs:
  release-matrix:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']

    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ github.ref_type == 'tag' && github.event.base_ref=='refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/client*
            target/release/server*
          prerelease: startsWith(github.ref_name, 'v0')
