on: pull_request

name: Continuous Integration

jobs:
  ci-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Continuous Integration - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install C build-dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update -qq
          sudo apt install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - name: Verify formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Verify build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all
      - name: Deny Clippy warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --tests -- -D warnings
      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --profile ci
