on: pull_request

name: CI
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  ci:
    name: Clash
    runs-on: ubuntu-latest
    steps:
      - name: Install C build-dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --profile=ci --no-run --locked
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --profile=ci
      - name: Deny Clippy warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --profile=ci --tests
      - name: Verify formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
